# This pipeline builds the documentation for the internal branch develop
pages:
  tags:
    - documentation
  image: alpine
  before_script:
    - apk update && apk add doxygen graphviz ttf-freefont texlive
  script:
    - rm -rf ./Documentation
    - doxygen Doxyfile
    - mv Documentation/html/ public/
  artifacts:
    paths:
      - public
  only:
    - develop
